FROM node:18

WORKDIR /usr/src/server

COPY package*.json ./
COPY src ./src
COPY typings ./typings
COPY tsconfig.json ./tsconfig.json

RUN npm ci
RUN npm run build
RUN npm prune --production

RUN rm -r src typings tsconfig.json

EXPOSE 3000

CMD ["npm", "run", "start"]
