export const API_ERROR_STATUS_CONST = {
  INVALID_BODY: 0,
  INVALID_PATH: 1,
  INVALID_QUERY: 2,
  NO_RESOURCE: 3,
  SERVER_ERROR: 4,
} as const;

export type API_ERROR_STATUS =
  (typeof API_ERROR_STATUS_CONST)[keyof typeof API_ERROR_STATUS_CONST];
