name: Run unit, integration and e2e tests
jobs:
  test:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/test')
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run type-check
        run: npm run build

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test
on:
  issue_comment:
    types:
      - created
      - edited
